/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bhavesh.ce2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Bhavesh kumar
 */
public class deposit extends javax.swing.JFrame {

    /**
     * Creates new form deposit
     */
    public deposit() {
        initComponents();
    }
     String s;
    public deposit(String s2) {
        initComponents();
        s=s2;
        Getbalance();
    }
    int obal;
    private void Getbalance(){
        try{
         Class.forName("com.mysql.jdbc.Driver");
                //Step2-Establish the Connection-db url,username,password
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ce2", "root", "22445");
                //Step3-Executing Query
                String qry="select balance from atm where pin='"+s+"'";
                Statement st =con.createStatement();
                ResultSet rs=st.executeQuery(qry);
                if(rs.next()){
                    obal=rs.getInt(1);
                    
                }
                else{
                    System.out.println("error");
                }}
                   catch (Exception e) {
                System.out.println("Error " + e.getMessage());
            }}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        l1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        l1.setText("Enter Your Amount:");

        b1.setText("Enter");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setText("Back");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(t1)
                    .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(131, 131, 131))
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b2)
                    .addComponent(b1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(l1)
                .addGap(18, 18, 18)
                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(b1)
                .addGap(18, 18, 18)
                .addComponent(b2)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        if(t1.getText().isEmpty() || t1.getText().equals(0)){
            JOptionPane.showMessageDialog(this,"Enter valid Amount ");
        }
        else{
        try {
                //Step1-Loading the driver for the Derby db in the memory
                Class.forName("com.mysql.jdbc.Driver");
                //Step2-Establish the Connection-db url,username,password
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ce2", "root", "22445");
                //Step3-Executing Query
                System.out.println("Connection Success");
                String temp=t1.getText();
                int amu=Integer.parseInt(temp);
                if(amu<=0)
                {
                    JOptionPane.showMessageDialog(this,"Invalid Amount");
                }
                else{
                int nbal=amu+obal;
                String nbal1=Integer.toString(nbal);
                
                
                PreparedStatement ps = con.prepareStatement("update atm set balance=? where pin ='"+s+"'");
                
                ps.setString(1, nbal1);
                
                ps.executeUpdate();  //Actually runs the query
                //l4.setText(("Student Information Updated Successfully"));
                JOptionPane.showMessageDialog(this,"Money Deposited Succesfully!!! ");
                }
            } catch (Exception e) {
                System.out.println("Error " + e.getMessage());
            }}
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if(evt.getSource()==b2){
    

    try {
                //Step1-Loading the driver for the Mysql db in the memory
                Class.forName("com.mysql.jdbc.Driver");
                //Step2-Establish the Connection-db url,username,password
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ce2", "root", "22445");
                System.out.println("Succesfull");
                dispose();
                mainf m=new mainf();
                m.show();
    } 
        catch (Exception e) {
                System.out.println("Error " + e.getMessage());
            }
        
    }
    
    }//GEN-LAST:event_b2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new deposit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JLabel l1;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
